apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-frontend
  namespace: churn-mlops
  labels:
    app: churn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-frontend
  template:
    metadata:
      labels:
        app: churn-frontend
    spec:
      containers:
        - name: churn-frontend
          image: ghcr.io/spurthipendyala/customerchurn_prediction/churn-frontend:sha-724d50f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: churn-frontend-svc
  namespace: churn-mlops
spec:
  selector:
    app: churn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
