global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'churn-mlops'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'churn-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
    scrape_interval: 30s
